from typing import Dict, List, Union

from pydantic import BaseModel, Field


class QueryResponse(BaseModel):
    """Structured response from the agent.

    Attributes:
        answer (str): Grounded answer generated by the agent.
        citations (List[Dict[str, Union[str, int, float]]]): Source indices and page numbers.
        visual_assets (List[str]): URLs or identifiers for diagrams/tables found.
        kb_id (str): The Knowledge Base that was used for the answer.
    """

    answer: str = Field(..., description="Grounded answer")
    citations: List[Dict[str, Union[str, int, float]]] = Field(
        ..., description="Source indices and page numbers"
    )
    visual_assets: List[str] = Field(
        ..., description="URLs or identifiers for diagrams/tables found"
    )
    kb_id: str = Field(..., description="The KB that was used for the answer")
